(() => {
  'use strict';

  const PROLOGUE_KEY='emberwild-prologue-v1';
  const ONBOARDING_KEY='emberwild-hearthcross-onboarding-v1';
  const PROFILE_KEY='emberwild-profile-v1';
  const SAVE_KEY='emberwild-save-v2';
  const OLD_SAVE_KEY='emberwild-save-v1';
  const canvas=document.getElementById('game');
  const ctx=canvas.getContext('2d');
  const hud=document.getElementById('hud');
  const quest=document.getElementById('quest');
  const overlay=document.getElementById('overlay');
  const toast=document.getElementById('toast');
  const interaction=document.getElementById('interaction');
  const TILE=32;
  const keys=new Set();
  const playerName=readName();

  const HOLLOW={
    w:80,h:44,
    paths:[
      [[6,30],[14,28],[22,29],[30,25],[38,24],[46,20],[55,21],[64,16],[74,13]],
      [[22,29],[22,20],[30,16],[38,24]],
      [[30,25],[35,34],[45,32],[46,20]],
      [[55,21],[60,29],[67,28],[64,16]]
    ],
    pockets:[[6,30,6.2],[15,28,4.5],[22,24,6.5],[30,18,5.5],[35,32,6.5],[40,24,6],[48,21,6],[55,21,7],[62,27,5.5],[65,16,7],[74,13,5]]
  };

  const state={
    stage:'intro',paused:true,last:performance.now(),walk:0,camera:{x:0,y:0},lastMove:{dx:1,dy:0},
    player:{x:6.2*TILE,y:30.2*TILE,hp:58,hpMax:58,potions:0,speed:170,weapon:null,inventory:[]},
    objects:{
      wake:{id:'wake',name:'Disturbed Ground',x:6.2*TILE,y:30.4*TILE,used:false},
      satchel:{id:'satchel',name:'Abandoned Satchel',x:11.5*TILE,y:29*TILE,used:false},
      marker:{id:'marker',name:'Weathered Trail Marker',x:16*TILE,y:27.8*TILE,used:false},
      herb:{id:'herb',name:'Silverleaf Patch',x:27*TILE,y:17.7*TILE,used:false},
      carcass:{id:'carcass',name:'Mauled Stag',x:33*TILE,y:25*TILE,used:false},
      claws:{id:'claws',name:'Claw-Marked Pine',x:35.5*TILE,y:22*TILE,used:false},
      camp:{id:'camp',name:'Wrecked Camp',x:54.5*TILE,y:20.4*TILE,used:false},
      overlook:{id:'overlook',name:'Smoke Beyond the Trees',x:64*TILE,y:16*TILE,used:false}
    },
    creatures:{
      stag:{id:'stag',kind:'forest_stag',name:'Forest Stag',x:25*TILE,y:21*TILE,alive:true,scanned:false},
      moss1:{id:'moss1',kind:'mossling',name:'Stray Mossling',x:40*TILE,y:23.5*TILE,alive:true,hp:42,hpMax:42,atk:5},
      moss2:{id:'moss2',kind:'mossling',name:'Mossling Pair',x:48*TILE,y:20.5*TILE,alive:true,hp:68,hpMax:68,atk:7},
      veilfang:{id:'veilfang',kind:'veilfang',name:'Unknown Entity',x:61*TILE,y:19*TILE,alive:true,hp:360,hpMax:360,atk:99}
    },
    battle:null,threat:{growl:false,shadow:false,scan:false},chase:{active:false,timer:0,target:{x:74*TILE,y:13*TILE}}
  };

  const slides=[
    {k:'SOMEWHERE ELSE',t:'You remember another world.',b:'Streetlights. A screen in your hand. A life that made sense right up until the instant it didn’t. Then came impact—white noise—nothing.'},
    {k:'NO SIGNAL',t:'Something finds you in the dark.',b:`<div class="prologue-system"><strong>SYSTEM INITIALIZATION</strong><br>Host consciousness: detected<br>Identity: <strong>${esc(playerName)}</strong><br>World designation: UNKNOWN<br>Compatibility: acceptable<br><br><strong>Recommendation: survive.</strong></div>`},
    {k:'EMBERWILD',t:'You wake beneath unfamiliar trees.',b:'No road signs. No phone signal. No idea how you got here. The forest smells wrong, the sky looks wrong, and a translucent prompt hangs at the edge of your vision.'}
  ];

  installStyles();
  queueMicrotask(boot);

  function readName(){try{return String(JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')?.name||'Wanderer').trim()||'Wanderer';}catch{return'Wanderer';}}
  function installStyles(){const s=document.createElement('style');s.textContent=`.prologue-card{max-width:780px}.prologue-system{border:1px solid #59745f;background:#09120d;padding:14px 16px;margin:14px 0;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#b9d9bd;box-shadow:inset 0 0 24px #0006}.prologue-system strong{color:#e9da8d}.prologue-slide{min-height:240px;display:flex;flex-direction:column;justify-content:center}.prologue-slide h2{font-size:30px;margin:0 0 14px}.prologue-slide p{font-size:15px;line-height:1.75;color:#bdc8c0}.prologue-kicker{font-size:11px;letter-spacing:.2em;color:#8fa798;text-transform:uppercase;margin-bottom:10px}.prologue-inventory{display:grid;grid-template-columns:1fr 1fr;gap:12px}.prologue-item{border:1px solid #33463a;background:#0a120e;padding:12px}.prologue-item.equipped{border-color:#d3b95f}.dialogue-name{color:#e2cc75;font-weight:800;margin-bottom:7px}.dialogue-copy{color:#c0cbc3;line-height:1.65}.prologue-danger{color:#e58b78!important}.prologue-fade{position:absolute;inset:0;background:#020302;display:grid;place-items:center;color:#d9e2dc;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.16em;z-index:10}.prologue-fade strong{font-size:22px}`;document.head.appendChild(s);}
  function boot(){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(OLD_SAVE_KEY);localStorage.removeItem(ONBOARDING_KEY);showSlide(0);requestAnimationFrame(loop);}
  function showSlide(i){state.paused=true;state.stage='intro';const s=slides[i];overlay.classList.remove('hidden');overlay.innerHTML=`<div class="modal prologue-card prologue-slide"><div class="prologue-kicker">${s.k}</div><h2>${s.t}</h2><div>${s.b}</div><div class="btn-row"><button class="primary" data-next>${i===slides.length-1?'Wake Up':'Continue'}</button></div></div>`;overlay.querySelector('[data-next]').onclick=()=>i<slides.length-1?showSlide(i+1):begin();}
  function begin(){state.paused=false;state.stage='inspect_wake';closeOverlay();notice('SYSTEM: Local environment scan incomplete. Assess your surroundings.',3400);updateUI();}
  function closeOverlay(){overlay.classList.add('hidden');overlay.innerHTML='';state.paused=false;}

  function walkable(px,py){const tx=px/TILE,ty=py/TILE;if(tx<1||ty<1||tx>HOLLOW.w-2||ty>HOLLOW.h-2)return false;for(const[cx,cy,r]of HOLLOW.pockets)if(Math.hypot(tx-cx,ty-cy)<=r)return true;for(const path of HOLLOW.paths)for(let i=0;i<path.length-1;i++)if(distSeg(tx,ty,...path[i],...path[i+1])<=2.7)return true;return false;}
  function distSeg(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,c1=vx*wx+vy*wy;if(c1<=0)return Math.hypot(px-x1,py-y1);const c2=vx*vx+vy*vy;if(c2<=c1)return Math.hypot(px-x2,py-y2);const b=c1/c2;return Math.hypot(px-(x1+b*vx),py-(y1+b*vy));}
  function update(dt){if(state.paused||state.stage==='intro')return;move(dt);events(dt);camera(dt);prompt();}
  function move(dt){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(!dx&&!dy)return;const l=Math.hypot(dx,dy);dx/=l;dy/=l;state.lastMove={dx,dy};state.walk+=dt*8;const speed=state.chase.active?195:state.player.speed,step=speed*dt,nx=state.player.x+dx*step,ny=state.player.y+dy*step;if(walkable(nx,state.player.y))state.player.x=nx;if(walkable(state.player.x,ny))state.player.y=ny;}
  function camera(dt){state.camera.x+=((state.player.x-canvas.width/2)-state.camera.x)*Math.min(1,dt*8);state.camera.y+=((state.player.y-canvas.height/2)-state.camera.y)*Math.min(1,dt*8);state.camera.x=Math.max(0,Math.min(HOLLOW.w*TILE-canvas.width,state.camera.x));state.camera.y=Math.max(0,Math.min(HOLLOW.h*TILE-canvas.height,state.camera.y));}
  function events(dt){const p=state.player,c=state.creatures;if(state.stage==='explore'&&(Math.hypot(p.x-state.objects.carcass.x,p.y-state.objects.carcass.y)<5*TILE||p.x/TILE>30)){state.stage='carcass';notice('SYSTEM: Biological remains detected near the trail.',2800);updateUI();}if(!c.stag.scanned&&Math.hypot(p.x-c.stag.x,p.y-c.stag.y)<3*TILE){c.stag.scanned=true;notice('SYSTEM SCAN: Forest Stag · Disposition: PASSIVE · Threat: Minimal',3600);}if(c.stag.alive&&Math.hypot(p.x-c.stag.x,p.y-c.stag.y)<2.5*TILE){const d=Math.max(1,Math.hypot(c.stag.x-p.x,c.stag.y-p.y)),nx=c.stag.x+(c.stag.x-p.x)/d*70*dt,ny=c.stag.y+(c.stag.y-p.y)/d*70*dt;if(walkable(nx,ny)){c.stag.x=nx;c.stag.y=ny;}}if(state.stage==='moss1'&&c.moss1.alive&&Math.hypot(p.x-c.moss1.x,p.y-c.moss1.y)<27)startBattle(c.moss1);if(state.stage==='moss2'&&c.moss2.alive&&Math.hypot(p.x-c.moss2.x,p.y-c.moss2.y)<27)startBattle(c.moss2);if(state.stage==='foreshadow'){const x=p.x/TILE;if(x>57&&!state.threat.growl){state.threat.growl=true;notice('Something growls beyond the trail. The Forest Stag bolts deeper into the trees.',3600,true);}if(x>60&&!state.threat.shadow){state.threat.shadow=true;notice('Movement detected beyond visual range.',2600,true);}if(x>62&&!state.threat.scan){state.threat.scan=true;state.stage='overlook';notice('SYSTEM: Entity detected... analyzing... ERROR: insufficient authority.',4200,true);updateUI();}}if(state.stage==='overlook'&&Math.hypot(p.x-state.objects.overlook.x,p.y-state.objects.overlook.y)<3*TILE){state.objects.overlook.used=true;state.stage='approach';notice('SYSTEM: Smoke source confirmed. Probable habitation ahead. Distance: 0.3 km.',4200);updateUI();}if(state.stage==='approach'&&p.x/TILE>67)startChase();if(state.chase.active){state.chase.timer+=dt;const v=c.veilfang,d=Math.max(1,Math.hypot(p.x-v.x,p.y-v.y));v.x+=(p.x-v.x)/d*135*dt;v.y+=(p.y-v.y)/d*135*dt;if(state.chase.timer>3.2&&state.chase.timer<3.35)notice('SYSTEM WARNING: Threat analysis failed. CURRENT RECOMMENDATION: RUN.',3600,true);if(Math.hypot(p.x-state.chase.target.x,p.y-state.chase.target.y)<2.5*TILE||state.chase.timer>=10||d<30){state.chase.active=false;startBattle(v);}}}

  function nearby(){const p=state.player;let best=null,d0=68;const use=o=>{if(!o||o.used)return;const d=Math.hypot(p.x-o.x,p.y-o.y);if(d<d0){best=o;d0=d;}};if(state.stage==='inspect_wake')use(state.objects.wake);if(state.stage==='satchel')use(state.objects.satchel);if(state.stage==='marker')use(state.objects.marker);if(!state.objects.herb.used)use(state.objects.herb);if(state.stage==='carcass')use(state.objects.carcass);if(state.stage==='claws')use(state.objects.claws);if(state.stage==='camp')use(state.objects.camp);return best;}
  function prompt(){if(state.battle){interaction.classList.add('hidden');return;}const n=nearby();if(n){interaction.textContent=`E — ${n.name}`;interaction.classList.remove('hidden');}else interaction.classList.add('hidden');}
  function interact(){if(state.paused||state.battle)return;const t=nearby();if(!t)return;if(t.id==='wake'){t.used=true;state.stage='satchel';notice('SYSTEM: Arrival signature unknown. Nearby object detected.',3200);}else if(t.id==='satchel'){t.used=true;state.player.potions=1;state.player.inventory.push({id:'knife',name:'Crude Trail Knife',type:'weapon',atk:6,equipped:false});state.stage='inventory';notice('Found: Crude Trail Knife · Field Tonic. Open your pack with I.',3600);}else if(t.id==='marker'){t.used=true;state.stage='explore';notice('SYSTEM TRANSLATION COMPLETE: HOLLOWPATH → EAST. Multiple routes detected.',3600);}else if(t.id==='herb'){t.used=true;state.player.potions++;notice('Optional discovery: Silverleaf. +1 rough restorative dose.',3000);}else if(t.id==='carcass'){t.used=true;state.stage='claws';dialogue('SYSTEM SCAN','Cause of death: severe trauma. Damage exceeds expected local predator profile. Nearby environmental trace detected.',updateUI);}else if(t.id==='claws'){t.used=true;state.stage='moss1';dialogue('SYSTEM','Claw depth exceeds current material estimate. Threat source: UNKNOWN. Recommendation: caution.',()=>{notice('Hostile contact detected ahead.',2400);updateUI();});}else if(t.id==='camp'){t.used=true;state.player.potions++;state.stage='foreshadow';dialogue('WRECKED CAMP','The tent has been ripped open from the outside. A mud-smeared scrap reads: “If anyone finds this, head for Hearthcross.” You salvage one intact tonic.',()=>{notice('OBJECTIVE UPDATED: Reach Hearthcross.',3000);updateUI();});}updateUI();}

  function openInventory(){if(state.paused||!['inventory','marker','explore','carcass','claws','moss1','moss2','camp','foreshadow','overlook','approach'].includes(state.stage))return;state.paused=true;const w=state.player.inventory.find(i=>i.type==='weapon');overlay.classList.remove('hidden');overlay.innerHTML=`<div class="modal narrow"><h2>Pack</h2><p class="subtitle">Items found in the world can be equipped or used from here.</p><div class="prologue-inventory"><div class="prologue-item ${w?.equipped?'equipped':''}"><h3>${w?.name||'Empty'}</h3><p>${w?`Weapon · +${w.atk} ATK`:'No weapon found.'}</p>${w&&!w.equipped?'<button class="primary" data-equip>Equip</button>':w?'<div class="small">Equipped</div>':''}</div><div class="prologue-item"><h3>Field Tonics</h3><p>${state.player.potions} restorative dose${state.player.potions===1?'':'s'}.</p></div></div><div class="btn-row"><button data-close>Close</button></div></div>`;const eq=overlay.querySelector('[data-equip]');if(eq)eq.onclick=()=>{w.equipped=true;state.player.weapon=w;state.stage='marker';closeOverlay();notice('Crude Trail Knife equipped. +6 ATK.',2200);updateUI();};overlay.querySelector('[data-close]').onclick=closeOverlay;}
  function dialogue(name,copy,done){state.paused=true;overlay.classList.remove('hidden');overlay.innerHTML=`<div class="modal prologue-card"><div class="dialogue-name">${name}</div><div class="dialogue-copy"><p>${copy}</p></div><div class="btn-row"><button class="primary" data-close>Continue</button></div></div>`;overlay.querySelector('[data-close]').onclick=()=>{closeOverlay();done?.();};}

  function startBattle(enemy){if(state.paused)return;state.paused=true;const veil=enemy.kind==='veilfang';state.battle={enemy,enemyHp:enemy.hpMax,turn:0,log:veil?['The thing steps into the clearing.','SYSTEM: Threat analysis failed.']:[`${enemy.name} blocks the path.`]};if(veil)state.stage='veil_battle';updateUI();renderBattle();}
  function renderBattle(){const b=state.battle,e=b.enemy,veil=e.kind==='veilfang';overlay.classList.remove('hidden');overlay.innerHTML=`<div class="modal"><h2>Battle — ${e.name}</h2><p class="subtitle">${veil?'LEVEL: ??? · THREAT: UNRESOLVED':'Tutorial encounter'}</p><div class="battle-grid"><div class="fighter"><div class="pixel-portrait">🧍</div><b>${esc(playerName)} · Unbound</b>${bar('HP',state.player.hp,state.player.hpMax)}</div><div class="fighter"><div class="pixel-portrait">${veil?'🐺':'🟢'}</div><b>${e.name}</b>${bar('HP',b.enemyHp,e.hpMax)}</div></div><div class="battle-log">${b.log.slice(-8).map(x=>`<div>› ${x}</div>`).join('')}</div>${veil?'<div class="prologue-danger">SYSTEM WARNING: Estimated level difference — EXTREME.</div>':''}<div class="btn-row"><button data-attack>Attack</button><button data-potion ${state.player.potions<=0?'disabled':''}>Potion (${state.player.potions})</button><button data-flee class="danger">Flee</button></div></div>`;overlay.querySelector('[data-attack]').onclick=attack;overlay.querySelector('[data-potion]').onclick=usePotion;overlay.querySelector('[data-flee]').onclick=flee;}
  function bar(l,c,m){const p=Math.max(0,Math.min(100,c/m*100));return`<div class="small">${l} ${Math.max(0,Math.round(c))}/${m}</div><div class="bar"><i style="width:${p}%"></i></div>`;}
  function attack(){const b=state.battle,e=b.enemy;if(e.kind==='veilfang'){const d=1+Math.floor(Math.random()*3);b.enemyHp-=d;b.log.push(`You strike for ${d}. It barely reacts.`);return enemyTurn();}const base=state.player.weapon?.equipped?14:8,d=base+Math.floor(Math.random()*4);b.enemyHp-=d;b.log.push(`You strike for ${d}.`);if(b.enemyHp<=0)return win();enemyTurn();}
  function enemyTurn(){const b=state.battle,e=b.enemy;b.turn++;if(e.kind==='veilfang'){if(b.turn===1)b.log.push('SYSTEM: Recalculating threat...');if(b.turn===2)b.log.push('SYSTEM WARNING: Survival probability 0.7%.');if(b.turn>=3){state.player.hp=0;b.log.push('The Veilfang moves faster than your vision can follow.');renderBattle();setTimeout(forcedDefeat,800);return;}const d=13+Math.floor(Math.random()*5);state.player.hp=Math.max(1,state.player.hp-d);b.log.push(`Veilfang tears through your guard for ${d}.`);renderBattle();return;}const d=e.atk+Math.floor(Math.random()*3);state.player.hp-=d;b.log.push(`${e.name} hits you for ${d}.`);if(state.player.hp<=0){state.player.hp=14;b.log.push('SYSTEM SAFEGUARD: Calibration failure prevented.');}renderBattle();}
  function usePotion(){if(state.player.potions<=0)return;state.player.potions--;state.player.hp=Math.min(state.player.hpMax,state.player.hp+26);state.battle.log.push('You drink a tonic and recover 26 HP.');enemyTurn();}
  function flee(){if(state.battle.enemy.kind==='veilfang'){state.battle.log.push('You turn to run. It is already cutting off the exit.');enemyTurn();}else{state.battle.log.push('SYSTEM: Finish this calibration encounter.');renderBattle();}}
  function win(){const e=state.battle.enemy;e.alive=false;state.battle=null;closeOverlay();state.player.hp=Math.min(state.player.hpMax,state.player.hp+5);if(e.id==='moss1'){state.stage='moss2';notice('Combat calibration complete. Loot: 1 Moss Gel. Another hostile group is moving near the eastern trail.',3800);}else{state.stage='camp';notice('SYSTEM: Smoke detected ahead. Probability of intelligent habitation: 73%.',4200);}updateUI();}
  function startChase(){state.stage='chase';state.chase.active=true;state.chase.timer=0;const v=state.creatures.veilfang;v.x=state.player.x-7*TILE;v.y=state.player.y+2*TILE;notice('ENTITY: UNKNOWN · THREAT ANALYSIS: FAILED · RUN.',4200,true);updateUI();}
  function forcedDefeat(){if(!state.battle||state.battle.enemy.kind!=='veilfang')return;state.battle=null;overlay.innerHTML='<div class="prologue-fade"><div><strong>CONSCIOUSNESS LOST</strong><br><br><span>Signal interrupted.</span></div></div>';setTimeout(finish,1300);}
  function finish(){const now=Date.now();localStorage.setItem(PROLOGUE_KEY,JSON.stringify({completed:true,hollowpathComplete:true,completedAt:now,rescuer:'Rhea',origin:'Hollowpath',playerName}));localStorage.setItem(ONBOARDING_KEY,JSON.stringify({version:1,stage:'wake',startedAt:now,playerName,hearthcrossStage:0,autoLaunchUntil:now+20000}));location.reload();}

  function updateUI(){const p=state.player;hud.innerHTML=`<div class="hud-chip">PATH<br><strong>Unbound</strong></div><div class="hud-chip">HP<br><strong>${Math.max(0,Math.round(p.hp))}/${p.hpMax}</strong></div><div class="hud-chip">Tonics<br><strong>${p.potions}</strong></div>`;const data={inspect_wake:['Second Life','Something about the ground where you woke is wrong.','Inspect the disturbed ground'],satchel:['Second Life','The System detected an abandoned object nearby.','Search the satchel'],inventory:['Second Life','You found your first weapon.','Press I and equip the Crude Trail Knife'],marker:['Second Life','A weathered marker stands beside the trail.','Inspect the trail marker'],explore:['Second Life','Side paths may hold useful discoveries.','Explore east and investigate anything unusual'],carcass:['Something Hunts Here','A dead stag lies near the trail.','Inspect the carcass'],claws:['Something Hunts Here','The System detected a matching environmental trace.','Inspect the claw-marked pine'],moss1:['Hostile Contact','A Mossling blocks the eastern route.','Defeat the Stray Mossling'],moss2:['Combat Calibration','Another hostile group is clustered farther east.','Defeat the Mossling Pair'],camp:['Smoke Ahead','Signs of habitation may be nearby.','Search the wrecked camp'],foreshadow:['Reach Hearthcross','The wrecked camp named a settlement beyond the forest.','Follow the eastern trail toward the smoke'],overlook:['Almost There','Smoke rises beyond the trees.','Reach the settlement'],approach:['Almost There','Smoke rises beyond the trees.','Reach the settlement'],chase:['RUN','The System cannot identify what is chasing you.','Reach the stone cut ahead'],veil_battle:['SURVIVE','Threat analysis has failed.','Find a way out']}[state.stage]||['Second Life','',''];quest.innerHTML=`<div class="quest-title">${data[0]}</div><div class="quest-text">${data[1]}</div><div class="quest-progress">${data[2]}</div>`;}
  function notice(msg,ms=2600,danger=false){toast.textContent=msg;toast.classList.remove('hidden');toast.style.borderColor=danger?'#8c4a41':'';toast.style.color=danger?'#f0a091':'';clearTimeout(toast._timer);toast._timer=setTimeout(()=>{toast.classList.add('hidden');toast.style.borderColor='';toast.style.color='';},ms);}

  function draw(){ctx.fillStyle='#07100b';ctx.fillRect(0,0,canvas.width,canvas.height);const cam=state.camera,x0=Math.max(0,Math.floor(cam.x/TILE)-2),y0=Math.max(0,Math.floor(cam.y/TILE)-2),x1=Math.min(HOLLOW.w,x0+Math.ceil(canvas.width/TILE)+4),y1=Math.min(HOLLOW.h,y0+Math.ceil(canvas.height/TILE)+4);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const sx=x*TILE-cam.x,sy=y*TILE-cam.y,w=walkable((x+.5)*TILE,(y+.5)*TILE),h=hash(x,y);ctx.fillStyle=w?(h>.55?'#3d593d':'#465d42'):(h>.5?'#183624':'#1d4029');ctx.fillRect(sx,sy,TILE+1,TILE+1);if(w&&h>.83)plant(sx+15,sy+20,h);}trees(cam,x0,y0,x1,y1,false);objects(cam);creatures(cam);player(cam);trees(cam,x0,y0,x1,y1,true);marker(cam);}
  function trees(cam,x0,y0,x1,y1,front){for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){if(walkable((x+.5)*TILE,(y+.5)*TILE))continue;const h=hash(x,y);if(h<=.35)continue;const base=y*TILE+22;if((base>state.player.y)!==front)continue;const sx=x*TILE+16-cam.x,sy=base-cam.y;if(window.EmberAssets?.draw(ctx,'prop.tree.pine',{x:sx,y:sy,w:48,h:64}))continue;ctx.fillStyle='#3e2d20';ctx.fillRect(sx-3,sy-12,6,18);ctx.fillStyle=h>.65?'#2f643b':'#275534';ctx.beginPath();ctx.arc(sx,sy-20,12,0,Math.PI*2);ctx.arc(sx-8,sy-14,9,0,Math.PI*2);ctx.arc(sx+8,sy-14,9,0,Math.PI*2);ctx.fill();}}
  function objects(cam){for(const o of Object.values(state.objects)){if(o.used||o.id==='overlook')continue;const x=o.x-cam.x,y=o.y-cam.y;if(o.id==='satchel'&&window.EmberAssets?.draw(ctx,'prop.satchel',{x,y,w:24,h:20}))continue;if(o.id==='marker'&&window.EmberAssets?.draw(ctx,'prop.sign',{x,y,w:32,h:40}))continue;ctx.fillStyle=o.id==='herb'?'#9bbf9d':o.id==='camp'?'#6f553d':'#8d7865';if(o.id==='wake'){ctx.strokeStyle='#667f70';ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.stroke();}else if(o.id==='camp'){ctx.beginPath();ctx.moveTo(x-20,y+10);ctx.lineTo(x,y-16);ctx.lineTo(x+20,y+10);ctx.fill();}else ctx.fillRect(x-10,y-7,20,14);}}
  function creatures(cam){for(const e of Object.values(state.creatures)){if(!e.alive)continue;if(e.kind==='veilfang'&&!['chase','veil_battle'].includes(state.stage))continue;const x=e.x-cam.x,y=e.y-cam.y,w=e.kind==='veilfang'?64:e.kind==='forest_stag'?48:e.id==='moss2'?44:32,h=e.kind==='veilfang'?56:e.kind==='forest_stag'?40:e.id==='moss2'?40:32;if(window.EmberAssets?.draw(ctx,`mob.${e.kind}`,{x,y,w,h}))continue;ctx.fillStyle=e.kind==='veilfang'?'#342936':e.kind==='forest_stag'?'#a98662':'#6faf68';ctx.fillRect(x-w/2,y-h+8,w,h-8);}}
  function player(cam){const x=state.player.x-cam.x,y=state.player.y-cam.y;if(window.EmberAssets?.draw(ctx,'player.wanderer',{x,y,w:32,h:48}))return;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(x,y+9,11,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#444746';ctx.fillRect(x-8,y-18,16,17);ctx.fillStyle='#56724f';ctx.fillRect(x-9,y-17,18,4);ctx.fillStyle='#b98765';ctx.fillRect(x-5,y-27,10,9);}
  function marker(cam){let t=null;const s=state.stage;if(s==='inspect_wake')t=state.objects.wake;else if(s==='satchel')t=state.objects.satchel;else if(s==='marker')t=state.objects.marker;else if(s==='carcass')t=state.objects.carcass;else if(s==='claws')t=state.objects.claws;else if(s==='moss1')t=state.creatures.moss1;else if(s==='moss2')t=state.creatures.moss2;else if(s==='camp')t=state.objects.camp;else if(['foreshadow','overlook','approach'].includes(s))t=state.objects.overlook;else if(s==='chase')t=state.chase.target;if(!t)return;const x=t.x-cam.x,y=t.y-cam.y-34+Math.sin(performance.now()/220)*3;ctx.fillStyle='#e7d56e';ctx.beginPath();ctx.moveTo(x,y+9);ctx.lineTo(x-7,y);ctx.lineTo(x+7,y);ctx.fill();}
  function plant(x,y,r){ctx.fillStyle=r>.93?'#d3c578':'#7ca773';ctx.fillRect(x,y-5,2,8);ctx.fillRect(x-4,y-2,4,2);ctx.fillRect(x+2,y-1,4,2);}
  function hash(x,y,s=0){let n=Math.imul((x+s*13)|0,374761393)^Math.imul((y-s*17)|0,668265263);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967295;}
  function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

  window.EmberRuntimeState={cartography:()=>({kind:'hollowpath',player:{x:state.player.x/TILE,y:state.player.y/TILE},paths:HOLLOW.paths,stage:state.stage})};
  function loop(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;update(dt);draw();requestAnimationFrame(loop);}
  window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){keys.add(k);e.preventDefault();}if(e.repeat)return;if(k==='e')interact();if(k==='i')openInventory();});
  window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
})();
